version: "3.2"

services:
  project_name_app: &app
    container_name: project_name
    tty: true
    build:
      context: ./project_name
      args:
        requirements: requirements/development.txt
    environment:
      # use in code
      - DJANGO_SETTINGS_MODULE=project_name.settings.local
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
      - static-django:/app/static:delegated
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    command: make -f project_name/Makefile _dev 

  postgres:
    image: postgres:12
    container_name: project_name_postgres
    environment:
      - POSTGRES_USER=project_name
      - POSTGRES_PASSWORD=project_name
      - POSTGRES_DB=project_name
    ports:
      - 5432

  redis:
    image: redis:6
    container_name: project_name_redis
    ports:
      - 6379
  
  nginx:
    hostname: project_name.development.com
    container_name: project_name_nginx
    restart: always
    build: 
      context: ./nginx
      args:
        - PUID=1001
        - PGID=1005
    ports: 
      - 80:80
    volumes:
      - static-django:/var/www/static-django
    command: > 
      bash -c "python3 /usr/local/src/services_check.py && nginx"

volumes: 
  static-django: